# Generated by Django 4.0.4 on 2022-05-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Employee_id', models.CharField(max_length=40)),
                ('Salary', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
