# Generated by Django 4.0.5 on 2022-06-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('Roll_No', models.CharField(max_length=40)),
                ('Year', models.IntegerField()),
                ('Branch', models.CharField(max_length=100)),
            ],
        ),
    ]
