# Generated by Django 4.0.4 on 2022-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cutomer_Name', models.CharField(max_length=50)),
                ('Cutomer_id', models.CharField(max_length=40)),
                ('Paid_Amount', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
